name: Deploy Azure Function

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: delivery-functions
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Clean
      run: dotnet clean Delivery.Functions/Delivery.Functions.csproj
      
    - name: Restore Function Project
      run: dotnet restore Delivery.Functions/Delivery.Functions.csproj

    - name: Build Function Project
      run: dotnet build Delivery.Functions/Delivery.Functions.csproj --configuration Release --no-restore

    - name: Publish Function Project
      run: |
        dotnet publish Delivery.Functions/Delivery.Functions.csproj \
          --configuration Release \
          --output ./publish

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: publish
