name: Deploy Delivery API

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: delivery-api
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore API Project
      run: dotnet restore Delivery.Api.csproj

    - name: Build API Project
      run: dotnet build Delivery.Api.csproj --configuration Release --no-restore

    - name: Publish API Project
      run: |
        dotnet publish Delivery.Api.csproj \
          --configuration Release \
          --output publish

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy API to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: publish
