name: Deploy to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Delivery.Api/Delivery.Api.csproj

      - name: Build
        run: dotnet build Delivery.Api/Delivery.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Delivery.Api/Delivery.Api.csproj -c Release -o ./publish --no-build

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'delivery-api-2'
          package: ./publish
